### ISSUE TITLE
Подсветить необходимость мониторинга свободного места на разделе /dev/shm

### ISSUE THREAD

**Issue by dbulashev** [lesovsky/postgresql-monitoring-book#7]
В книге предлагается использовать тестовое окружение в виде сервисов на основе docker контейнеров.
На практике контейнеры удобны и для промышленной эксплуатации. Одной из целей контейниризации является гибкое разграничение ресурсов.

В докер контейнерах по-умолчанию размер shared memory ограничен 64 мегабайтами.
Изменить его можно несколькими способами:

1. Указание размера shared memory в `/etc/docker/daemon.json`
```json
{
  "default-shm-size": "512M"
}
```

2. Параметр `--shm-size` при запуске контейнера через команду `docker run`

```shell
docker run --rm -it --name ubuntu --shm-size=2gb ubuntu
```

3. При деплое через `docker-compose up` в параметрах сервиса
```yaml
version: '3.9'
services:
  db:
    image: postgres
    shm_size: 128mb
```

4. При деплое docker Swarm через `docker stack deploy`  в параметрах volume

```yaml
version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
```

PostgreSQL использует /dev/shm для обмена данными между параллельными запросами
При нехватке свободного места будут возникать ошибки:
`ERROR:  could not resize shared memory segment . . . : No space left on device`

Поэтому я считаю, что стоит подсветить вопросы мониторинга раздела shared memory в Вашей книге.
